[package]
name = "prometheus"
version = "0.6.0"
license = "Apache-2.0"
keywords = ["prometheus", "metrics"]
authors = ["overvenus@gmail.com", "siddontang@gmail.com", "vistaswx@gmail.com"]
description = "Prometheus instrumentation library for Rust applications."
readme = "README.md"
repository = "https://github.com/pingcap/rust-prometheus"
homepage = "https://github.com/pingcap/rust-prometheus"
documentation = "https://docs.rs/prometheus"
edition = "2018"

[badges]
travis-ci = { repository = "pingcap/rust-prometheus" }

[package.metadata.docs.rs]
features = ["nightly"]

[features]
default = ["codec-protobuf"]
nightly = ["libc"]
push = ["reqwest", "libc"]
process = ["libc", "procinfo"]
gen = ["protobuf-build"]
codec-protobuf = ["protobuf"]
codec-prost = ["bytes", "prost", "prost-derive", "protobuf"]

[dependencies]
protobuf = { version = "2.0", optional = true }
quick-error = "1.2.2"
fnv = "1.0"
lazy_static = "1.1.0"
libc = { version = "0.2", optional = true }
cfg-if = "0.1"
spin = { version = "0.5", default-features = false }
reqwest = { version = "0.9.5", optional = true }
bytes = { version = "0.4", optional = true }
prost = { version = "0.5", optional = true }
prost-derive = { version = "0.5", optional = true }


[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { version = "0.3", optional = true }

[dev-dependencies]
getopts = "0.2"
hyper = { version = "0.9", default-features = false }

[build-dependencies]
protobuf-build = { version = "0.2", optional = true }

[workspace]
members = ["static-metric"]
